name: Check Issues
on:
  issues:
    types: [opened]
jobs:
    check-issue:
        runs-on: ubuntu-latest
        steps: 
          - name: Output Github context
            run: |
                echo "Issue number: ${{ github.event.issue.number }}"
                echo "Title: ${{ github.event.issue.title }}"
                echo "Body: ${{ github.event.issue.body }}"
                echo "Author: ${{ github.event.issue.user.login }}"
